### PR TITLE
Fix #1546, revert wrong changes and request system messages

### LINKED ISSUE #1546: 当机器人账号设置为允许任何人添加好友时，mirai的联系人缓存机制会导致Bot.getFriends()抛出异常无法找到新添加的好友。
当机器人账号设置为允许任何人添加好友时，mirai的联系人缓存机制会导致Bot.getFriends()抛出异常无法找到新添加的好友。重启项目后再次运行Bot.getFriends()又可以找到好友了。

因生产环境...并没有详细的日志。希望能提供好友申请事件时自动刷新缓存的功能

```

```

#### 复现

1. 设置允许任何人添加好友后登录机器人。
2. 任意账号添加机器人为好友。
3. 调用getFriend方法会抛出无法找到联系人的异常

#### 版本及相关选项选择

- mirai-core: `2.7` 
- bot-protocol: `ANDROID_PHONE` 

#### 网络日志

```

```

### PR DESCRIPTION
**Pull request by sandtechnology**
…ing stranger

### CODE REVIEW

File: mirai-core/src/commonMain/kotlin/network/notice/priv/FriendNoticeProcessor.kt [hunk 1]
```diff
@@ -80,15 +81,20 @@ internal class FriendNoticeProcessor(
         }
 
         msgHead.context {
-            if (fromUin == authUin) {
-                logger.error { "Could not determine uin since `fromUin` = `authUin` = $fromUin" }
+            // 对方 qq
+            val id = sequenceOf(fromUin, authUin).firstOrNull { it != 0L && it != bot.id }
```
Comment (Him188) [inline mirai-core/src/commonMain/kotlin/network/notice/priv/FriendNoticeProcessor.kt]:
```suggestion
            val id = longArrayOf(fromUin, authUin).firstOrNull { it != 0L && it != bot.id }
```
更快

**Review by Him188 — APPROVED** [review]

**Review by Karlatemp — APPROVED** [review]
