### PR TITLE
[console] Fix plugins disabling

### LINKED ISSUE #2015: `JvmPlugin.onDisable` 会执行多次

### PR DESCRIPTION
**Pull request by Karlatemp**
Fix #2015, see commits for details

### CODE REVIEW

File: mirai-console/backend/mirai-console/src/internal/plugin/JvmPluginInternal.kt [hunk 1]
```diff
@@ -47,6 +49,68 @@ internal val <T> T.job: Job where T : CoroutineScope, T : Plugin get() = this.co
...
+        ;
+
+        internal companion object {
+            internal val ALLOWED_TO_SWITCH_TO_DISABLE = EnumSet.of(
+                CRASHED_LOAD_ERROR,
+                CRASHED_ENABLE_ERROR,
+                ENABLED,
+            )
+        }
+    }
```
Comment (Him188) [inline mirai-console/backend/mirai-console/src/internal/plugin/JvmPluginInternal.kt]: 应该给 enum 加一个属性 `val allowedToSwitchToDisable`, 否则未来增加状态可能会忘记考虑这个

File: mirai-console/backend/mirai-console/src/internal/plugin/JvmPluginInternal.kt [hunk 2]
```diff
@@ -47,6 +49,68 @@ internal val <T> T.job: Job where T : CoroutineScope, T : Plugin get() = this.co
...
+            if (pluginStatus.compareAndSet(expect = nowStatus, update = update)) {
+                return
+            }
+            error("Failed to switch plugin '$id' status from $nowStatus to $update, current status = ${pluginStatus.value}")
+        }
+        error("Failed to switch plugin '$id' status from one status of $expect to $update, current status = $nowStatus")
+    }
+
+    @JvmSynthetic
+    internal fun switchStatusOrFailed(expect: PluginStatus, update: PluginStatus) {
```
Comment (Him188) [inline mirai-console/backend/mirai-console/src/internal/plugin/JvmPluginInternal.kt]:
```suggestion
    internal fun switchStatusOrFail(expect: PluginStatus, update: PluginStatus) {
```

File: mirai-console/backend/mirai-console/src/internal/plugin/JvmPluginInternal.kt [hunk 3]
```diff
@@ -47,6 +49,68 @@ internal val <T> T.job: Job where T : CoroutineScope, T : Plugin get() = this.co
...
+    private val pluginStatus = atomic(PluginStatus.ALLOCATED)
+
+    @get:JvmSynthetic
+    internal val currentPluginStatus: PluginStatus get() = pluginStatus.value
+
+    final override val isEnabled: Boolean
+        get() = pluginStatus.value === PluginStatus.ENABLED
+
+    @JvmSynthetic
+    internal fun switchStatusOrFailed(expect: Collection<PluginStatus>, update: PluginStatus) {
```
Comment (Him188) [inline mirai-console/backend/mirai-console/src/internal/plugin/JvmPluginInternal.kt]:
```suggestion
    internal fun switchStatusOrFail(expect: Collection<PluginStatus>, update: PluginStatus) {
```

**Review by Him188 — CHANGES_REQUESTED** [review]

**Review by Him188 — APPROVED** [review]

**Comment by Him188** [comment]
Squash or merge, on your decision.
