### PR TITLE
Fix inconsistent message length

### LINKED ISSUE #195: 权重值是否设置不当？
> 长消息判定权重, 具体为: Chinese char=4, English char=1, Quote=700, Image=800

上限为5000，并且QQ对这个上限的判断为字符并非字节，中文字符应该也为1
如果我发送全是Image的消息，那么就只能发送6张图片，远低于原先可发送的50张图片
能否将Image的值调低，比如100呢

### LINKED ISSUE #539: 群聊中艾特人数较多时报错
```

java.lang.IllegalStateException: Send group message failed: MessageSvcPbSendMsg.Response.Failed(resultType=34, errorCode=0, errorMessage=)
	at net.mamoe.mirai.qqandroid.contact.GroupImpl.sendMessageImpl(GroupImpl.kt:369)
	at net.mamoe.mirai.qqandroid.contact.GroupImpl$sendMessageImpl$1.invokeSuspend(GroupImpl.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)


```

#### 版本
mirai: `1.2.2 `

### PR DESCRIPTION
**Pull request by sandtechnology**

### CODE REVIEW

File: mirai-core/src/commonMain/kotlin/utils/type.kt [hunk 1]
```diff
@@ -48,10 +46,10 @@ internal fun MessageChain.estimateLength(target: ContactOrBot, upTo: Int): Int =
 internal fun SingleMessage.estimateLength(target: ContactOrBot, upTo: Int): Int {
     return when (this) {
         is QuoteReply -> 444 + this.source.originalMessage.estimateLength(target, upTo) // Magic number
-        is Image -> 260 // Magic number
+        is Image -> 40 //magic number
         is PlainText -> content.chineseLength(upTo)
-        is At -> this.getDisplay(target.safeCast()).chineseLength(upTo)
-        is AtAll -> display.chineseLength(upTo)
+        is At -> 60 //magic number
+        is AtAll -> 5 //magic number
```
Comment (Him188) [inline mirai-core/src/commonMain/kotlin/utils/type.kt:52]: 建议保守估计 AtAll
```suggestion
        is AtAll -> 60 //magic number
```

**Review by Him188 — CHANGES_REQUESTED** [review]

**Review by Him188 — APPROVED** [review]
